name: ldcpy-docs
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - cartopy
  - xarray
  - scipy
  - matplotlib
  - pip
  - pip:
      - sphinx
      - sphinx_rtd_theme
      - nbsphinx
      - sphinx-reload
      - pillow
      - ipython
      - -r ../requirements.txt
      - -e ..
